# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbe1dd38d1866d6f7e3baeabc5d38ddfff6863f7393e5f504bbee881d993badf86915c08576e5bda5f2d3ee487395118b2b3f97079f27026e08950a2845e8c4e

test:
  secret_key_base: d4711d82f1716fe632c82c4d59537011c1e43d53c2fb452d8d4043b6c4e21ebce6cbf37b46497e6b9e947444aca661b7d25052b5b799647e86f4c9f866f07de9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
